services:

  jaeger:
    image: jaegertracing/all-in-one:1.53
    restart: 'no'
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
      - SPAN_STORAGE_TYPE=badger
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    user: root
    volumes:
      - ./volumes/jaeger:/badger


  postgres:
    image: postgres:alpine
    restart: 'no'
    env_file:
      - env/postgres.env
    volumes:
      - ./volumes/pg:/var/lib/postgresql/data/pgdata:rw
      - ./bootstrap/postgres:/docker-entrypoint-initdb.d:ro
    ports:
      - 5432:5432

  krakend:
    image: devopsfaith/krakend:2.5-watch
    restart: 'no'
    command: ["run", "-dc", "krakend.tmpl"]
    env_file:
      - env/krakend.env
    ports:
      - 8080:8080
    volumes:
      - ./conf/krakend:/etc/krakend

  api-token-dev:
    image: node:20.5-alpine
    restart: 'no'
    entrypoint: "npm"
    command: ["run", "start:dev"]
    env_file:
      - env/token.env
    volumes:
      - ../../services:/devroot
    user: "1000:1000"
    working_dir: /devroot/token
    ports:
      - 7100:7100
      - 9200:9200

  api-basic-auth-dev:
    image: node:20.5-alpine
    restart: 'no'
    entrypoint: "npm"
    command: [ "run", "start:dev" ]
    env_file:
      - env/basic-auth.env
    volumes:
      - ../../services:/devroot
    user: "1000:1000"
    working_dir: /devroot/basic-auth
    ports:
      - 7101:7101
      - 9201:9201


