import {
    AddNotificationContext,
    AuthContext, CoreAdminContext,
    CreateContext,
    DataProviderContext,
    EditContext,
    I18nContext,
    ListContext,
    ListFilterContext,
    ListPaginationContext,
    ListSortContext,
    NotificationContext,
    PreferencesEditorContext,
    RecordContext,
    ResourceContext,
    ResourceDefinitionContext,
    SaveContext,
    ShowContext,
    ThemesContext,
} from 'react-admin';
import { UNSAFE_LocationContext, UNSAFE_NavigationContext, UNSAFE_RouteContext } from 'react-router';
import { Context } from 'react';

export const SharingContexts: (Context<any> | undefined)[] = [
    RecordContext,
    SaveContext,
    CreateContext,
    ListPaginationContext,
    ListSortContext,
    ListFilterContext,
    ListContext,
    ResourceContext,
    ShowContext,
    EditContext,
    ResourceDefinitionContext,
    AddNotificationContext,
    NotificationContext,
    I18nContext,
    PreferencesEditorContext,
    DataProviderContext,
    AuthContext,
    UNSAFE_RouteContext,
    UNSAFE_LocationContext,
    UNSAFE_NavigationContext,
    ThemesContext,
];
